# Differentiation in Python : Symbolic , Numerical and Automatic

- You will perform symbolic differentiation with `SymPy` library
- Numerical with `NumPy`
- automatic with `JAX`(based on `Autograd`)

## 1 - Functions in Python  

In [2]:
# defining a function f = x^2
def f(x):
    return x**2
print(f(3))

9


In [3]:
# derivative of a function f = 2x
def dfdx(x):
    return 2*x
print(dfdx(3))

6


In [6]:
# applying a function to every element of an array
import numpy as np

x_array = np.array([1,2,3])

print("\nx: \n", x_array)
print("\nf(x) = x**2: \n", f(x_array))
print("\nf'(x) = 2x: \n", dfdx(x_array))



x: 
 [1 2 3]

f(x) = x**2: 
 [1 4 9]

f'(x) = 2x: 
 [2 4 6]



In real life the functions are more complicated and it is not possible to calculate the derivatives analytically every time.

So let's explore which tools and library are avaialble in python for computing the derivatives without manaul derivation.

## 2 - Symbolic Differentiation

**Symbolic computation** deals with the computation of mathematical objects that are represented exactly, not approximately (e.g. $\sqrt{2}$ will be written as it is, not as $1.41421356237$). For differentiation it would mean that the output will be somehow similar to if you were computing derivatives by hand using rules (analytically). Thus, symbolic differentiation can produce exact derivatives.

In [8]:
import math
math.sqrt(18)

4.242640687119285

In [10]:
from sympy import *
sqrt(18)

3*sqrt(2)

The above is the Symbolic Calculation ,but you can also get the numeric one and by how much decimal youc an decide that

In [12]:
N(sqrt(18),8)

4.2426407

### In SymPy variables are defined using `Symbols`

Expression : $2x^2 - xy$


In [14]:
x, y = symbols("x y")

expr = 2*(x**2) - x*y
expr

2*x**2 - x*y

In [15]:
expr_manip = x * (expr + x * y + x**3)
expr_manip

x*(x**3 + 2*x**2)

In [16]:
expand(expr_manip)

x**4 + 2*x**3

In [17]:
factor(expr_manip)

x**3*(x + 2)

In [19]:
# substitution in function $2x^2 - xy$
expr.evalf(subs={x:-1, y:2})

4.00000000000000

In [22]:
# evaluation a functionn f = x^2
f_symb = x**2
f_symb.evalf(subs={x:3}) # adding x=3 in the function f

9.00000000000000

### 2-1. Symbolic Differentiation with SymPy

let's try to find derivative of ${x^3}$

In [29]:
diff(x**3,x) # here second param means wrt x

3*x**2

In [33]:
exp(x)

exp(x)

In [34]:
diff(exp(x),x)

exp(x)

In [39]:
dfdx_symb = diff(expr_manip, x)
dfdx_symb

x**3 + 2*x**2 + x*(3*x**2 + 4*x)

✅ NumPy generally deals with numerical values.

✅ SymPy can keep the expression symbolic:

### 2-2. Limitation of Symbolic Differentation


Symbolic Differentiation seems to be a great tool. But it also has some limitations. Sometimes the output expressions are too complicated and even not possible to evaluate. For example, find the derivative of the function $$\left|x\right| = \begin{cases} x, \ \text{if}\ x > 0\\  -x, \ \text{if}\ x < 0 \\ 0, \ \text{if}\ x = 0\end{cases}$$ Analytically, its derivative is:
$$\frac{d}{dx}\left(\left|x\right|\right) = \begin{cases} 1, \ \text{if}\ x > 0\\  -1, \ \text{if}\ x < 0\\\ \text{does not exist}, \ \text{if}\ x = 0\end{cases}$$

Have a look the output from the symbolic differentiation:

In [41]:
dfdx_abs = diff(abs(x),x)
dfdx_abs

(re(x)*Derivative(re(x), x) + im(x)*Derivative(im(x), x))*sign(x)/x

## 3 - Automatc Differentiation with JAX

In [46]:
from jax import grad, vmap
import jax.numpy as jnp

In [47]:
f(3)

9

In [51]:
print("Function value at x = 3:", f(3.0))
print("Derivative value at x = 3:",grad(f)(3.0))

Function value at x = 3: 9.0
Derivative value at x = 3: 6.0
