# Introduction to the Numpy.linalg sub-library

- Use `NumPy` linear algebra package to find the solution to the system of linear equations.
- Evaluate the determinant of the matrix to see again the connection between matrix singularity and the number of solutions of the linear system.
- Exlpore the numpy.linalg sub-library to get to know its properties.

In [1]:
import numpy as np

## 1 - Representing & Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

<a name='1.1'></a>
### 1.2 - Solving System of Linear Equations using Matrices

In [5]:
A = np.array([
        [4,-3,1],
        [2,1,3],
        [-1,2,-5]
    ], dtype='float')

b = np.array([-10,0,17],dtype='float')

print("\nMatrix A : \n")
print(A)

print("\nArray b : \n")
print(b)


Matrix A : 

[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b : 

[-10.   0.  17.]


Checking dimensions of A and b using .shape

In [6]:
print(f"Shape of Matrix A : {A.shape}") # (3,3)
print(f"Shape of Array b : {b.shape}") # (3,)

Shape of Matrix A : (3, 3)
Shape of Array b : (3,)


Now use `np.linalg.solve(A, b)` function to find the solution of the system $(1)$. The result will be saved in the 1-D array $x$. The elements will correspond to the values of $x_1$, $x_2$ and $x_3$:

In [7]:
x = np.linalg.solve(A,b)
print(f"Solution : {x}")

Solution : [ 1.  4. -2.]


<a name='1.3'></a>
### 1.3 - Evaluating the Determinant of a Matrix

Matrix $A$ corresponding to the linear system $(1)$ is a **square matrix** - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix $A$ has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:

In [11]:
d = np.linalg.det(A)
print(f"Determinant of matrix A : {d:.2f}")

Determinant of matrix A : -60.00


The determinant is non zero as expected as we have unique solution

<a name='1.4'></a>
### 1.4 - What happens if the system has no unique solution?

Let's explore what happens if we use `np.linalg.solve` in a system with no unique solution (no solution at all or infinitely many solutions).

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [12]:
A_2= np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

print(np.linalg.solve(A_2, b_2))

LinAlgError: Singular matrix

As you can see, it throws a `LinAlgError` because the matrix is singular. You can check this for yourself by computing the determinant of the matrix:

In [13]:
d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


NOTE : Remember that `np.linalg.solve` gives an error if there are no or infinitely many solutions. When using it, you will need to check for that case to prevent your program from crashing.