# Introduction to Python Matrices and NumPy #

Welcome to your first notebook of this specialization! In this notebook, you will use NumPy to create 2-D arrays and easily compute mathematical operations. NumPy (Numerical Python) is an open-source package that is widely used in science and engineering. Feel free to skip this notebook if you are already fluent with NumPy.

**After this assignment you will be able to:**
- Use Jupyter Notebook and its features. 
- Use NumPy functions to create arrays and NumPy array operations. 
- Use indexing and slicing for 2-D arrays.
- Find the shape of an array, reshape it and stack it horizontally and vertically.


<a name='1'></a>
# 1 -  Basics of Numpy

In [7]:
import numpy as np

<a name='1-1'></a>
### 1-1 Different way of creating one dim numpy array ##

In [8]:
# array method
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

<a name='1-2'></a>
### 1-2 Change the data type of an element

In [13]:
spaced_array = np.linspace(0,10,5)
# check the data type
spaced_array.dtype


dtype('float64')

In [14]:
# change from float64 to int
spaced_array.astype(int)

array([ 0,  2,  5,  7, 10])

In [17]:
char_array = np.array(["Welcome to Math for ML!"])
print(char_array)
print(char_array.dtype) # Output: <U23 => 23-character unicode string (U)

['Welcome to Math for ML!']
<U23


<a name='1-3'></a>
### 1-3 More on Numpy array ###

- `np.ones()`  - Returns a new array setting values to one
- `np.zeros()`  - Returns a new array setting values to zero
- `np.empty()`  - Returns a new array but does not initialize the elements. The array may contain arbitrary (garbage) values already present in memory.
- `np.random.rand()`  - Returns a new array with values choosen at random

In [20]:
np.random.rand(3) # select 3 random value from 0 to 1

array([0.23321813, 0.60629953, 0.24125983])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.empty(3)

array([1., 1., 1.])

<a name='2'></a>
# 2 - Multi Dimentional Array

In [30]:
# create a two dim array
two_dim_arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [33]:
# create a 1 dim array and rehape it to 2 dim array
one_dim_arr = np.array([5,3,2,6,7,2])
two_dim_arr = one_dim_arr.reshape((2,3)) # 2 rows and 3 col

In [34]:
print(one_dim_arr)
print(two_dim_arr)

[5 3 2 6 7 2]
[[5 3 2]
 [6 7 2]]


<a name='2-1'></a>
### 2-1  Finding size, shape, and dimension

In [35]:
two_dim_arr.ndim

2

In [37]:
two_dim_arr.shape # 2 rows, 3 columns

(2, 3)

In [38]:
two_dim_arr.size # total count of an element in an array

6

<a name='3'></a>
# 3 - Array Math Operation

In [41]:
arr1 = np.array([5,3,6,7])
arr2 = np.array([5,4,1,2])

# addtition
addition = np.add(arr1,arr2)
# subtraction
subtraction = np.subtract(arr1,arr2) 
# multiplication
multipication = np.multiply(arr1,arr2)

print("addition",addition)
print("subtraction",subtraction)
print("multipication",multipication)

addition [10  7  7  9]
subtraction [ 0 -1  5  5]
multipication [25 12  6 14]


<a name='3-1'></a>
## 3-1 Multiplying vector with scalar (broadcasting)

In [43]:
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

<a name='4'></a>
# 4 - Indexing and Slicing

Allows us to select specific elements from an array. You can select certain portion as well

<a name='4-1'></a>
## 4-1 Indexing ##

In [46]:
## 1-dim indexing
arr1 = np.array([4,5,2,3,1])
print(arr1[2])
# select the first and last element
print("First ele is :", arr1[0])
print("Last ele is :", arr1[-1])


2
First ele is : 4
Last ele is : 1


In [49]:
# 2-dim indexing
arr2 = np.array([ [4,2,1] ,[5,2,7] ])
# selecting 0th row and last col , value is 1
print(arr2[0][-1])
# we can select in this way as well
print(arr2[0,-1])

1
1


<a name='4-2'></a>
## 4-2 Slicing ##

It helps us to select the subset of element that you specify from the array.

Syntax : `array[start:end:step]`


In [51]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [52]:
# selecting 4,5,6
arr[1,:]

array([4, 5, 6])

In [53]:
# getting last 2 row
arr[-2:,:]

array([[4, 5, 6],
       [7, 8, 9]])

<a name='5'></a>
# 5 - Stacking

It allows you to join array vertically or horizontally

In [55]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [56]:
# vertical stacking
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [57]:
# horizontal stacking
hori_stack = np.hstack((a1,a2))
print(hori_stack)

[[1 1 3 3]
 [2 2 4 4]]
