## 1️⃣ Matrix Multiplication Using Python

In [2]:
import numpy as np

In [3]:
# defining matrix A and B
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [4]:
# Matrix multiplication of A and B
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [5]:
# we can also use @ symbol to do matrix multiplication
A@B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

## 2️⃣ Matrix Convention and Broadcasting

Mathematically Matrix multiplication is defined only if number of columns of Matrix `A` is equal to the numbers of the rows of matrix `B` .

Thus , in the above example Matrix `A` and `B` , We can perform matrix multiplication of `AB` as the shape of `A` is (3x3) and the shape of `B` is (3x2).

In [7]:
# trying to do matrix multiplication of BA
try:
    np.matmul(B,A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [8]:
try:
    B @ A
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


So when using matrix multiplication you will need to be very careful about the dimensions - the number of the columns in the first matrix should match the number of the rows in the second matrix. This is very important for your future understanding of Neural Networks and how they work. 

However, for multiplying of the vectors, `NumPy` has a shortcut. You can define two vectors $x$ and $y$ of the same size (which one can understand as two $3 \times 1$ matrices). If you check the shape of the vector $x$, you can see that :

In [9]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)
print("Shape of vector x, reshaped to a matrix:", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshaped to a matrix:", x.reshape((3, 1)).ndim)

Shape of vector x: (3,)
Number of dimensions of vector x: 1
Shape of vector x, reshaped to a matrix: (3, 1)
Number of dimensions of vector x, reshaped to a matrix: 2


In [15]:
np.matmul(x,y)

np.int64(3)

In [18]:
# now if we change the shape and try to do multiplication but the dimension dont match then
try:
    np.matmul(x.reshape((3, 1)), y.reshape((3, 1)))
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


#### Does np.dot(A,B) also works ?

Ans =  Yes it does!

In [19]:
np.dot(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

## 3️⃣ Broadcasting

Broadcasting is applying the operation to all the element of a matrices.
It is like we are sending what operation to apply to each element whithout changing the shape of the matrix

In [21]:
A

array([[4, 9, 9],
       [9, 1, 6],
       [9, 2, 3]])

In [23]:
# broadcasting
A-2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])