A linear transformation is a function that transforms a vector from one vector space to another that respect the underlying (linear) structure of each vector space.

Referring to a specific transformation , you can use a symbol, such as `T`.

A Transformation can change the Vector Space , so from 2-dim spaced vector a transformation can transform it to 3-dim or any dim vector space.

You can write $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$.

Transforming vector $v \in \mathbb{R}^2$ into the vector $w\in\mathbb{R}^3$ by the transformation $T$, you can use the notation $T(v)=w$ and read it as "*T of v equals to w*" or "*vector w is an **image** of vector v with the transformation T*".

The following Python function corresponds to the transformation $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ with the following symbolic formula:

$$T\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}
          \tag{1}
          $$

In [3]:
import numpy as np

## 1️⃣ Transformation

In [7]:
def T(v):
    w = np.zeros((3,1))
    # making first row first col as 3*v_1
    w[0,0] = 3 * v[0,0]
    # making third row first col as -2*v_2
    w[2,0] = -2* v[1,0]
    
    return w
    
v = np.array([
    [3],
    [5]
])

w = T(v)
print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)


Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9.]
 [  0.]
 [-10.]]


<a name='2'></a>
## 2️⃣ Linear Transformation

A transformation $T$ is said to be **linear** if the following two properties are true for any scalar $k$, and any input vectors $u$ and $v$:

1. $T(kv)=kT(v)$,
2. $T(u+v)=T(u)+T(v)$.

In the example above $T$ is a linear transformation:

$$T (kv) =
          T \begin{pmatrix}\begin{bmatrix}
          kv_1 \\
          kv_2
          \end{bmatrix}\end{pmatrix} = 
          \begin{bmatrix}
           3kv_1 \\
           0 \\
           -2kv_2
          \end{bmatrix} =
          k\begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} = 
          kT(v),\tag{2}$$
          
$$T (u+v) =
          T \begin{pmatrix}\begin{bmatrix}
          u_1 + v_1 \\
          u_2 + v_2
          \end{bmatrix}\end{pmatrix} = 
          \begin{bmatrix}
           3(u_1+v_1) \\
           0 \\
           -2(u_2+v_2)
          \end{bmatrix} = 
          \begin{bmatrix}
           3u_1 \\
           0 \\
           -2u_2
          \end{bmatrix} +
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix} = 
          T(u)+T(v).\tag{3}$$

In [12]:
u = np.array([[1], [-2]])
v = np.array([[2], [4]])

k = 7

print("T(k*v):\n", T(k*v), "\n\n k*T(v):\n", k*T(v), "\n\n")
print("T(u+v):\n", T(u+v), "\n\n T(u)+T(v):\n", T(u)+T(v))

T(k*v):
 [[ 42.]
 [  0.]
 [-56.]] 

 k*T(v):
 [[ 42.]
 [  0.]
 [-56.]] 


T(u+v):
 [[ 9.]
 [ 0.]
 [-4.]] 

 T(u)+T(v):
 [[ 9.]
 [ 0.]
 [-4.]]


<a name='3'></a>
## 3 - Transformations Defined as a Matrix Multiplication

Let $L: \mathbb{R}^m \rightarrow \mathbb{R}^n$ be defined by a matrix $A$, where $L(v)=Av$, multiplication of the matrix $A$ ($n\times m$) and vector $v$ ($m\times 1$) resulting in the vector $w$ ($n\times 1$).

Now try to guess, what should be the elements of matrix $A$, corresponding to the transformation $L: \mathbb{R}^2 \rightarrow \mathbb{R}^3$:

$$L\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}=
          \begin{bmatrix}
           ? & ? \\
           ? & ? \\
           ? & ?
          \end{bmatrix}
          \begin{bmatrix}
           v_1 \\
           v_2
          \end{bmatrix}
          \tag{4}
          $$

To do that, write the transformation $L$ as $Av$ and then perform matrix multiplication:
    $$L\begin{pmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}\end{pmatrix}=
          A\begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}=
          \begin{bmatrix}
           a_{1,1} & a_{1,2} \\
           a_{2,1} & a_{2,2} \\
           a_{3,1} & a_{3,2}
          \end{bmatrix}
          \begin{bmatrix}
           v_1 \\           
           v_2
          \end{bmatrix}=
          \begin{bmatrix}
           a_{1,1}v_1+a_{1,2}v_2 \\
           a_{2,1}v_1+a_{2,2}v_2 \\
           a_{3,1}v_1+a_{3,2}v_2 \\
          \end{bmatrix}=
          \begin{bmatrix}
           3v_1 \\
           0 \\
           -2v_2
          \end{bmatrix}\tag{5}
          $$
          
Can you see now what should be the values of the elements $a_{i,j}$ of matrix $A$ to make the equalities $(5)$ correct? Find out the answer in the following code cell:

We can solve and find that the Matrix A will be as below :

In [18]:
def L(v):
    # this is the transformation matrix
    A = np.array([ [3,0],[0,0],[0,-2]])
    print("Transformation matrix:\n", A, "\n")
    # multiplication of a Matrix with a vector
    return np.matmul(A,v)
v = np.array([ [3],[5] ])
w = L(v)

print("Original vector:\n", v, "\n\n Result of the transformation:\n", w)

Transformation matrix:
 [[ 3  0]
 [ 0  0]
 [ 0 -2]] 

Original vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9]
 [  0]
 [-10]]


## 4 -  Simple Idea Behind This

A 2×2 matrix $A$ is fully decided by just **two things**:
- Where it sends $e_1=\begin{bmatrix}1\\0\end{bmatrix}$
- Where it sends $e_2=\begin{bmatrix}0\\1\end{bmatrix}$

Why? Because any vector is just a mix of $e_1$ and $e_2$. For example:
$$\begin{bmatrix}3\\5\end{bmatrix} = 3e_1 + 5e_2$$

So if $L$ is linear:
$$L\left(\begin{bmatrix}3\\5\end{bmatrix}\right) = 3L(e_1) + 5L(e_2)$$

This means: **knowing $L(e_1)$ and $L(e_2)$ is enough to know $L$ for every vector.**

## The Shortcut

$$A = \begin{bmatrix} L(e_1) & L(e_2) \end{bmatrix}$$

In plain words: **$L(e_1)$ is column 1 of $A$, and $L(e_2)$ is column 2 of $A$.**

## Why

$$Ae_1 = \begin{bmatrix}a_{1,1} & a_{1,2}\\a_{2,1} & a_{2,2}\end{bmatrix}\begin{bmatrix}1\\0\end{bmatrix} = \begin{bmatrix}a_{1,1}\\a_{2,1}\end{bmatrix}$$

That's just column 1. The same works for $Ae_2$ → column 2.

## Takeaway

Instead of guessing the formula for $A$, just ask:
- "Where does $(1,0)$ go?" → column 1
- "Where does $(0,1)$ go?" → column 2

That's it — this is why $e_1$ and $e_2$ are used to *visualize* transformations later.

<a name='4.1'></a>
### 4.1 - Example 1: Horizontal Scaling (Dilation)

Horizontal scaling (factor $2$ in this example) can be defined considering transformation of a vector $e_1=\begin{bmatrix}1 \\ 0\end{bmatrix}$ into a vector $\begin{bmatrix}2 \\ 0\end{bmatrix}$ and leaving vector $e_2=\begin{bmatrix}0 \\ 1\end{bmatrix}$ without any changes. The following function `T_hscaling()` corresponds to the horizontal scaling (factor $2$) of a vector. The second function `transform_vectors()` applies defined transformation to a set of vectors (here two vectors).

In [20]:
def T_hscaling(v):
    A = np.array([ [2,0] ,[0,1] ])
    w = A@v
    return w

def transform_vectors(T,v1,v2):
    V =np.hstack((v1,v2))
    W = T(V)
    return W
    
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

transformation_result_hscaling = transform_vectors(T_hscaling, e1, e2)

print("Original vectors:\n e1= \n", e1, "\n e2=\n", e2, 
      "\n\n Result of the transformation (matrix form):\n", transformation_result_hscaling)


Original vectors:
 e1= 
 [[1]
 [0]] 
 e2=
 [[0]
 [1]] 

 Result of the transformation (matrix form):
 [[2 0]
 [0 1]]


<a name='4.2'></a>
### 4.2 - Example 2: Reflection about y-axis (the vertical axis)

- **Reflection about the y-axis** → $x \to -x$, $y \to y$ (negate x-coordinate, keep y-coordinate)
- **Reflection about the x-axis** → $x \to x$, $y \to -y$ (negate y-coordinate, keep x-coordinate)

In [26]:
def reflection_y_axis(v):
    A = np.array([ [-1,0],[0,1] ])
    w = A * v
    return w
#basis vectors
e1 = np.array([[1],[0]])
e2 = np.array([[0],[1]])

V = np.hstack((e1,e2))
reflection_y_axis(V)


array([[-1,  0],
       [ 0,  1]])